<?php
/**
 * Plugin-local error logger.
 *
 * @package Dragwyb_Click_To_Chat
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'DCTC_Error_Logger' ) ) {
	/**
	 * Stores recent plugin errors for display in the admin settings tab.
	 */
	class DCTC_Error_Logger {

		const OPTION_NAME = 'dctc_error_logs';
		const MAX_LOGS    = 200;

		/**
		 * Prevent recursive writes while logging.
		 *
		 * @var bool
		 */
		private static $is_logging = false;

		/**
		 * Any error handler that existed before this logger was attached.
		 *
		 * @var callable|null
		 */
		private static $previous_error_handler = null;

		/**
		 * Attach handlers.
		 *
		 * @return void
		 */
		public static function init() {
			self::$previous_error_handler = set_error_handler( array( __CLASS__, 'handle_php_error' ) );
			register_shutdown_function( array( __CLASS__, 'handle_shutdown' ) );

			if ( is_admin() ) {
				add_action( 'wp_ajax_dctc_clear_error_logs', array( __CLASS__, 'ajax_clear_logs' ) );
			}
		}

		/**
		 * Log PHP warnings/notices/errors generated by this plugin.
		 *
		 * @param int    $errno   Error number.
		 * @param string $errstr  Error message.
		 * @param string $errfile File path.
		 * @param int    $errline Line number.
		 * @return bool False so PHP/WordPress can continue normal error handling.
		 */
		public static function handle_php_error( $errno, $errstr, $errfile = '', $errline = 0 ) {
			if ( self::should_log_file( $errfile ) ) {
				self::log(
					self::error_type_label( $errno ),
					$errstr,
					array(
						'file' => $errfile,
						'line' => $errline,
						'code' => $errno,
					)
				);
			}

			if ( is_callable( self::$previous_error_handler ) ) {
				return (bool) call_user_func( self::$previous_error_handler, $errno, $errstr, $errfile, $errline );
			}

			return false;
		}

		/**
		 * Log fatal shutdown errors generated by this plugin.
		 *
		 * @return void
		 */
		public static function handle_shutdown() {
			$error = error_get_last();

			if ( empty( $error ) || empty( $error['type'] ) ) {
				return;
			}

			$fatal_types = array( E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR, E_USER_ERROR, E_RECOVERABLE_ERROR );
			if ( ! in_array( $error['type'], $fatal_types, true ) ) {
				return;
			}

			$file = isset( $error['file'] ) ? $error['file'] : '';
			if ( ! self::should_log_file( $file ) ) {
				return;
			}

			self::log(
				self::error_type_label( $error['type'] ),
				isset( $error['message'] ) ? $error['message'] : __( 'Unknown fatal error.', 'dragwyb-click-to-chat' ),
				array(
					'file' => $file,
					'line' => isset( $error['line'] ) ? $error['line'] : 0,
					'code' => $error['type'],
				)
			);
		}

		/**
		 * Add an entry to the stored log.
		 *
		 * @param string $type    Error type.
		 * @param string $message Error message.
		 * @param array  $context Optional context.
		 * @return void
		 */
		public static function log( $type, $message, $context = array() ) {
			if ( self::$is_logging ) {
				return;
			}

			self::$is_logging = true;

			$logs = self::get_logs();

			$entry = array(
				'id'         => uniqid( 'dctc_', true ),
				'type'       => sanitize_text_field( (string) $type ),
				'message'    => wp_strip_all_tags( (string) $message ),
				'file'       => isset( $context['file'] ) ? self::relative_plugin_path( (string) $context['file'] ) : '',
				'line'       => isset( $context['line'] ) ? absint( $context['line'] ) : 0,
				'code'       => isset( $context['code'] ) ? sanitize_text_field( (string) $context['code'] ) : '',
				'context'    => isset( $context['context'] ) ? sanitize_text_field( (string) $context['context'] ) : '',
				'created_at' => current_time( 'mysql' ),
			);

			array_unshift( $logs, $entry );
			$logs = array_slice( $logs, 0, self::MAX_LOGS );

			update_option( self::OPTION_NAME, $logs, false );

			self::$is_logging = false;
		}

		/**
		 * Return recent log entries.
		 *
		 * @param int $limit Maximum rows.
		 * @return array
		 */
		public static function get_logs( $limit = self::MAX_LOGS ) {
			$logs = get_option( self::OPTION_NAME, array() );
			$logs = is_array( $logs ) ? $logs : array();

			return array_slice( $logs, 0, max( 0, absint( $limit ) ) );
		}

		/**
		 * Clear all logs.
		 *
		 * @return void
		 */
		public static function clear_logs() {
			delete_option( self::OPTION_NAME );
		}

		/**
		 * AJAX endpoint to clear logs.
		 *
		 * @return void
		 */
		public static function ajax_clear_logs() {
			check_ajax_referer( 'dctc_nonce', 'nonce' );

			if ( ! current_user_can( 'manage_options' ) ) {
				wp_send_json_error( array( 'message' => __( 'You do not have permission to clear logs.', 'dragwyb-click-to-chat' ) ), 403 );
			}

			self::clear_logs();
			wp_send_json_success();
		}

		/**
		 * Should a PHP error from this file be stored?
		 *
		 * @param string $file File path.
		 * @return bool
		 */
		private static function should_log_file( $file ) {
			if ( empty( $file ) || ! defined( 'DCTC_PLUGIN_DIR' ) ) {
				return false;
			}

			$file       = wp_normalize_path( $file );
			$plugin_dir = wp_normalize_path( DCTC_PLUGIN_DIR );

			return 0 === strpos( $file, $plugin_dir );
		}

		/**
		 * Convert an absolute plugin path to a concise relative path.
		 *
		 * @param string $file Absolute path.
		 * @return string
		 */
		private static function relative_plugin_path( $file ) {
			if ( empty( $file ) || ! defined( 'DCTC_PLUGIN_DIR' ) ) {
				return '';
			}

			$file       = wp_normalize_path( $file );
			$plugin_dir = wp_normalize_path( DCTC_PLUGIN_DIR );

			if ( 0 === strpos( $file, $plugin_dir ) ) {
				return ltrim( substr( $file, strlen( $plugin_dir ) ), '/' );
			}

			return $file;
		}

		/**
		 * Convert a PHP error code to a readable label.
		 *
		 * @param int $errno Error number.
		 * @return string
		 */
		private static function error_type_label( $errno ) {
			$labels = array(
				E_ERROR             => 'Fatal Error',
				E_WARNING           => 'Warning',
				E_PARSE             => 'Parse Error',
				E_NOTICE            => 'Notice',
				E_CORE_ERROR        => 'Core Error',
				E_CORE_WARNING      => 'Core Warning',
				E_COMPILE_ERROR     => 'Compile Error',
				E_COMPILE_WARNING   => 'Compile Warning',
				E_USER_ERROR        => 'User Error',
				E_USER_WARNING      => 'User Warning',
				E_USER_NOTICE       => 'User Notice',
				E_STRICT            => 'Strict Standards',
				E_RECOVERABLE_ERROR => 'Recoverable Error',
				E_DEPRECATED        => 'Deprecated',
				E_USER_DEPRECATED   => 'User Deprecated',
			);

			return isset( $labels[ $errno ] ) ? $labels[ $errno ] : 'PHP Error';
		}
	}
}

if ( ! function_exists( 'dctc_log_error' ) ) {
	/**
	 * Convenience wrapper for handled plugin errors.
	 *
	 * @param string $type    Error type.
	 * @param string $message Error message.
	 * @param array  $context Optional context.
	 * @return void
	 */
	function dctc_log_error( $type, $message, $context = array() ) {
		if ( class_exists( 'DCTC_Error_Logger' ) ) {
			DCTC_Error_Logger::log( $type, $message, $context );
		}
	}
}
