<?php
/**
 * Global Admin Helper Class for Dragwyb Click to Chat.
 *
 * Provides shared utility methods across all plugin admin pages
 * including AI Assistant, Channels, Support Center, Guide, and Settings.
 *
 * @package Dragwyb_Click_To_Chat
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( 'DCTC_Helper' ) ) {

	/**
	 * Class DCTC_Helper
	 */
	class DCTC_Helper {

		/**
		 * Initialize helper hooks.
		 *
		 * @return void
		 */
		public static function init() {
			if ( is_admin() ) {
				add_action( 'admin_print_scripts', array( __CLASS__, 'hide_unrelated_admin_notices' ) );
				add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_common_assets' ), 5 );
			}
		}

		/**
		 * Enqueue common styles and design tokens across all plugin admin pages.
		 *
		 * @return void
		 */
		public static function enqueue_common_assets() {
			if ( ! self::is_plugin_admin_page() ) {
				return;
			}

			wp_enqueue_style( 'dashicons' );
			wp_enqueue_style(
				'dctc-common-style',
				DCTC_PLUGIN_URL . 'assets/css/common.css',
				array( 'dashicons' ),
				DCTC_VERSION
			);
		}

		/**
		 * Check if the current admin screen belongs to the plugin.
		 * Matches Support Center, AI Assistant, Channels, Guide, and Settings pages.
		 *
		 * @return bool
		 */
		public static function is_plugin_admin_page() {
			if ( ! is_admin() ) {
				return false;
			}

			// phpcs:ignore WordPress.Security.NonceVerification.Recommended
			$page = isset( $_GET['page'] ) ? sanitize_text_field( wp_unslash( $_GET['page'] ) ) : '';

			if ( empty( $page ) ) {
				return false;
			}

			$plugin_pages = array(
				// AI Assistant & Channels pages
				'dragwyb-click-to-chat',
				'dragwyb-click-to-chat-channels',
				'dragwyb-click-to-chat-guide',
				'dragwyb-click-to-chat-settings',
				'dragwyb-click-to-chat-support',
				// Support Center pages
				'dragwyb-support-center',
				'dragwyb-support-tickets',
				'dragwyb-support-agents',
				'dragwyb-support-taxonomies',
				'dragwyb-support-settings',
			);

			if ( in_array( $page, $plugin_pages, true ) ) {
				return true;
			}

			// Check prefix for dynamic or future subpages
			if ( 0 === strpos( $page, 'dragwyb-click-to-chat' ) || 0 === strpos( $page, 'dragwyb-support-' ) ) {
				return true;
			}

			return false;
		}

		/**
		 * Hide unrelated third-party and core admin notices on all plugin pages.
		 *
		 * @return void
		 */
		public static function hide_unrelated_admin_notices() {
			if ( ! self::is_plugin_admin_page() ) {
				return;
			}

			global $wp_filter;

			$notice_hooks = array(
				'user_admin_notices',
				'admin_notices',
				'all_admin_notices',
			);

			foreach ( $notice_hooks as $hook_name ) {
				if (
					empty( $wp_filter[ $hook_name ] ) ||
					empty( $wp_filter[ $hook_name ]->callbacks ) ||
					! is_array( $wp_filter[ $hook_name ]->callbacks )
				) {
					continue;
				}

				foreach ( $wp_filter[ $hook_name ]->callbacks as $priority => $callbacks ) {
					foreach ( $callbacks as $callback_id => $callback_data ) {
						if ( empty( $callback_data['function'] ) ) {
							continue;
						}

						unset(
							$wp_filter[ $hook_name ]->callbacks[ $priority ][ $callback_id ]
						);
					}
				}
			}

			// Remove delayed admin notices generated by WordPress.
			if (
				isset( $wp_filter['admin_footer']->callbacks ) &&
				is_array( $wp_filter['admin_footer']->callbacks )
			) {
				foreach ( $wp_filter['admin_footer']->callbacks as $priority => $callbacks ) {
					foreach ( $callbacks as $callback_id => $callback_data ) {
						if (
							isset( $callback_data['function'] ) &&
							'render_delayed_admin_notices' === $callback_data['function']
						) {
							unset(
								$wp_filter['admin_footer']->callbacks[ $priority ][ $callback_id ]
							);
						}
					}
				}
			}

			// Register this plugin's notices after unrelated notices have been removed.
			// phpcs:ignore WordPress.Security.NonceVerification.Recommended
			$page = isset( $_GET['page'] ) ? sanitize_text_field( wp_unslash( $_GET['page'] ) ) : '';
			add_action(
				'admin_notices',
				function () use ( $page ) {
					self::display_admin_notices( $page );
				},
				PHP_INT_MAX
			);
		}

		/**
		 * Display plugin-specific admin notices.
		 *
		 * @param string $current_page Current admin page slug.
		 * @return void
		 */
		public static function display_admin_notices( $current_page = '' ) {
			do_action( 'dctc_admin_notices', $current_page );

			if ( 0 === strpos( $current_page, 'dragwyb-support-' ) || 'dragwyb-support-center' === $current_page ) {
				do_action( 'dctc_support_admin_notices', $current_page );
			}
		}

		/**
		 * Check whether the Social Channels Widget module is enabled.
		 *
		 * @return bool
		 */
		public static function is_channels_enabled() {
			$settings = get_option( 'dctc_settings', array() );
			if ( ! is_array( $settings ) ) {
				return true;
			}
			return ! isset( $settings['channels_enabled'] ) || '1' === (string) $settings['channels_enabled'] || true === $settings['channels_enabled'];
		}

		/**
		 * Check whether the AI Assistant module is enabled.
		 *
		 * @return bool
		 */
		public static function is_ai_enabled() {
			$ai_settings = get_option( 'dctc_ai_chat_assistant_settings', array() );
			if ( ! is_array( $ai_settings ) ) {
				return false;
			}
			return ! empty( $ai_settings['display']['entire_site'] );
		}

		/**
		 * Check whether the Support Center module is enabled.
		 *
		 * @return bool
		 */
		public static function is_support_enabled() {
			$support_settings = get_option( 'dctc_support_settings', array() );
			if ( ! is_array( $support_settings ) ) {
				return false;
			}
			return ! empty( $support_settings['enabled'] );
		}
	}
}
